---
functional:
  - Возможность менять язык программирования во время решения
  - В игру можно играть с любым человеком, ботом или другом (игра будет доступна по ссылке)
  - Можно выбрать игру по уровню сложности
  - При создании игры можно выбрать определенное задание
  - Завершенная игра доступна в записи
  - По завершению игры выдаются очки рейтинга
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы