---
functional:
  - Возможность менять язык программирования во время игры
  - В игру можно играть с любым пользователем, ботом или другом (игра будет доступна по ссылке)
  - Можно создать игру с выбором уровня сложности
  - При создании игры можно выбрать определенное задание
  - Завершенная игра доступна в записи
  - По завершению игры выдаются очки рейтинга
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузера
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
